### ISSUE TITLE
Upgrade is failing

### ISSUE THREAD

**Issue by nagkumar** [LordMaduz/spring-boot-3-open-telemetey-series#6]
```
 :: Spring Boot ::                (v3.1.5)

09:35:57.299 [main] INFO  com.teja.sb.otel.WFluxOTelApp - Starting WFluxOTelApp using Java 17.0.10 with PID 2
204 (F:\nag\DWork\osource\experiments\java\spring-boot\otel\02\wflux\target\classes started by nagku in F:\nag\DWork\osource\experiments\java\spring-boot\otel\02\wflux)
09:35:57.303 [main] INFO  com.teja.sb.otel.WFluxOTelApp - No active profile set, falling back to 1 default profile: "default"
09:35:58.369 [main] WARN  o.s.b.w.r.c.AnnotationConfigReactiveWebServerApplicationContext - Exception encount
ered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.Unsatisfie
dDependencyException: Error creating bean with name 'openTelemetry' defined in class path resource [com/teja/
sb/otel/cfgs/OTelCFG.class]: Unsatisfied dependency expressed through method 'openTelemetry' parameter 0: Err
or creating bean with name 'otelSdkLoggerProvider' defined in class path resource [com/teja/sb/otel/cfgs/OTel
CFG.class]: Failed to instantiate [io.opentelemetry.sdk.logs.SdkLoggerProvider]: Factory method 'otelSdkLoggerProvider' threw exception with message: io/opentelemetry/sdk/internal/ScopeConfigurator
09:35:58.386 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLogger - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
09:35:58.403 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'openTelemetr
y' defined in class path resource [com/teja/sb/otel/cfgs/OTelCFG.class]: Unsatisfied dependency expressed thr
ough method 'openTelemetry' parameter 0: Error creating bean with name 'otelSdkLoggerProvider' defined in cla
ss path resource [com/teja/sb/otel/cfgs/OTelCFG.class]: Failed to instantiate [io.opentelemetry.sdk.logs.SdkL
oggerProvider]: Factory method 'otelSdkLoggerProvider' threw exception with message: io/opentelemetry/sdk/internal/ScopeConfigurator
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at com.teja.sb.otel.WFluxOTelApp.main(WFluxOTelApp.java:13)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelSdkLog
gerProvider' defined in class path resource [com/teja/sb/otel/cfgs/OTelCFG.class]: Failed to instantiate [io.
opentelemetry.sdk.logs.SdkLoggerProvider]: Factory method 'otelSdkLoggerProvider' threw exception with message: io/opentelemetry/sdk/internal/ScopeConfigurator
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
        ... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.sdk.
logs.SdkLoggerProvider]: Factory method 'otelSdkLoggerProvider' threw exception with message: io/opentelemetry/sdk/internal/ScopeConfigurator
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
        ... 33 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/sdk/internal/ScopeConfigurator
        at io.opentelemetry.sdk.logs.internal.LoggerConfig.configuratorBuilder(LoggerConfig.java:56)
        at io.opentelemetry.sdk.logs.SdkLoggerProviderBuilder.<init>(SdkLoggerProviderBuilder.java:38)       
        at io.opentelemetry.sdk.logs.SdkLoggerProvider.builder(SdkLoggerProvider.java:48)
        at com.teja.sb.otel.cfgs.OTelCFG.otelSdkLoggerProvider(OTelCFG.java:45)
        at com.teja.sb.otel.cfgs.OTelCFG$$SpringCGLIB$$0.CGLIB$otelSdkLoggerProvider$1(<generated>)
        at com.teja.sb.otel.cfgs.OTelCFG$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.teja.sb.otel.cfgs.OTelCFG$$SpringCGLIB$$0.otelSdkLoggerProvider(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
        ... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.sdk.internal.ScopeConfigurator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)        
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 48 common frames omitted
[INFO] -----------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ----------------------------------------------------------------------------------------------------- 
[INFO] Total time:  6.114 s
[INFO] Finished at: 2024-05-15T09:35:58+05:30
[INFO] ----------------------------------------------------------------------------------------------------- 
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.1.5:start (default-cli) on
 project wflux: Failed to connect to MBean server at port 9001: Could not invoke shutdown operation: Connection refused to host: 127.0.0.1; nested exception is:
[ERROR]         java.net.ConnectException: Connection refused: connect
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch
[ERROR] Re-run Maven using the '-X' switch to enable verbose output
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:    
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

my pom upgraded is  

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>3.1.5</version>
	<relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.reactive.optl</groupId>
    <artifactId>wflux</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <description>Demo project for Spring Boot and OpenTelemetry</description>
    <properties>
	<java.version>17</java.version>
    </properties>
    <dependencies>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-webflux</artifactId>
	</dependency>
	<dependency>
	    <groupId>org.springdoc</groupId>
	    <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
	    <version>2.5.0</version>
	</dependency>
	<dependency>
	    <groupId>org.projectlombok</groupId>
	    <artifactId>lombok</artifactId>
	    <optional>true</optional>
	</dependency>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-test</artifactId>
	    <scope>test</scope>
	</dependency>
	<dependency>
	    <groupId>io.micrometer</groupId>
	    <artifactId>micrometer-registry-otlp</artifactId>
	    <scope>runtime</scope>
	</dependency>
	<dependency>
	    <groupId>io.micrometer</groupId>
	    <artifactId>micrometer-tracing-bridge-otel</artifactId>
	    <version>1.3.0</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-api</artifactId>
	    <version>1.38.0</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-exporter-otlp</artifactId>
	    <version>1.38.0</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-exporter-common</artifactId>
	    <version>1.38.0</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry.instrumentation</groupId>
	    <artifactId>opentelemetry-logback-appender-1.0</artifactId>
	    <version>2.3.0-alpha</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-sdk</artifactId>
	    <version>1.38.0</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry.instrumentation</groupId>
	    <artifactId>opentelemetry-instrumentation-api-semconv</artifactId>
	    <version>1.33.2-alpha</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-exporter-otlp-common</artifactId>
	    <version>1.38.0</version>
	</dependency>
	<dependency>
	    <groupId>io.netty</groupId>
	    <artifactId>netty-all</artifactId>
	</dependency>
    </dependencies>

    <build>
	<plugins>
	    <plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<configuration>
		    <excludes>
			<exclude>
			    <groupId>org.projectlombok</groupId>
			    <artifactId>lombok</artifactId>
			</exclude>
		    </excludes>
		</configuration>
	    </plugin>
	</plugins>
    </build>
</project>

```

**Comment by nagkumar** [comment]
failes with with all the versions of opentelemetry other than 1.31.0... including 1.32.0, 1.33, ...1.38 the latest one

**Comment by LordMaduz** [comment]
Hi @nagkumar 
Thanks for reaching out and pointing.
This is due to some transitive dependencies inside **io.opentelemetry** will still point to default version pointed by Spring which is **1.31.0**.
To fix this include 
`<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-bom</artifactId>
				<version>1.38.0</version>
				<type>pom</type>
				<scope>runtime</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
`

Also we need to upgrade respective micrometer dependencies as well because if you inspect dependencies like **micrometer-tracing-bridge-otel** it has **io.opentelemetry** dependencies as transitive dependencies.

**Comment by LordMaduz** [comment]
The updated pom.file

[pom.txt](https://github.com/LordMaduz/spring-boot-3-open-telemetey-series/files/15335857/pom.txt)

**Comment by LordMaduz** [comment]
I am closing this as this works fine after the Pom upgrade.

**Comment by nagkumar** [comment]
Thank You, in the file attached by you, these two are 1.33.2-alpha hope that is correct version
```
<dependency>
	    <groupId>io.opentelemetry.instrumentation</groupId>
	    <artifactId>opentelemetry-logback-appender-1.0</artifactId>
	    <version>1.33.2-alpha</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry.instrumentation</groupId>
	    <artifactId>opentelemetry-instrumentation-api-semconv</artifactId>
	    <version>1.33.2-alpha</version>
	</dependency>
```

**Comment by LordMaduz** [comment]
Yes, they do. I tested locally.
